DB_NAME: todolist
DB_HOST: 127.0.0.1
DB_PORT: 5432
DB_USERNAME: admin
DB_PASSWORD: password

spring:
  application.name: r2dbc-todo-list-app
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    locations: classpath:db/migration
    baseline-on-migrate: true

logging.level.org.springframework.data.r2dbc: debug